# Generated by Django 3.0.5 on 2020-04-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='data',
            new_name='system_data',
        ),
    ]
