# Generated by Django 3.0.5 on 2020-04-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200406_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledata',
            name='depressed',
            field=models.BooleanField(default=False),
        ),
    ]
