# Generated by Django 3.0.5 on 2020-04-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profiledata_depressed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='profile_data_type',
            field=models.CharField(choices=[('A', 'Age'), ('G', 'Gender'), ('L', 'Location'), ('P', 'Personality'), ('D', 'Depression')], max_length=1),
        ),
    ]
