# Generated by Django 3.0.5 on 2020-04-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200409_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
