# Generated by Django 3.0.5 on 2020-04-09 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200409_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='api.Profile'),
        ),
    ]
