# Generated by Django 3.0.5 on 2020-05-07 13:24

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200415_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledata',
            name='location',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
