# Generated by Django 3.0.5 on 2020-06-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200601_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_retrieved_comment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
