# Generated by Django 3.0.5 on 2020-06-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200601_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experiment_id',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reddit_username',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
