# Generated by Django 3.0.5 on 2020-06-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200601_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_in_progress', models.BooleanField(default=False)),
                ('task_id', models.TextField(max_length=100)),
            ],
        ),
    ]
