# Generated by Django 3.0.5 on 2020-06-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_globaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaldata',
            name='task_id',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
