# Generated by Django 3.0.5 on 2020-06-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200607_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledata',
            name='age',
            field=models.TextField(choices=[('12-20', '12-20'), ('20-30', '20-30'), ('30-65', '30-65'), ('65+', '65+'), ('Unknown', 'Unknown')], default='Unknown'),
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='personality',
            field=models.TextField(choices=[('Extraversion', 'Extraversion'), ('Agreeableness', 'Agreeableness'), ('Conscientiousness', 'Conscientiousness'), ('Neuroticism', 'Neuroticism'), ('Openness', 'Openness'), ('Unknown', 'Unknown')], default='Unknown'),
        ),
    ]
