# Generated by Django 3.0.5 on 2020-07-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200629_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledata',
            name='depressed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
