# Generated by Django 3.0.5 on 2020-11-09 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200712_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus_name', models.TextField(max_length=1000, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='age',
            field=models.TextField(choices=[('12-20', '12-20'), ('20-30', '20-30'), ('30-65', '30-65'), ('Over65', 'Over65'), ('Unknown', 'Unknown')], default='Unknown'),
        ),
        migrations.AddField(
            model_name='profile',
            name='corpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_corpus', to='api.Corpus'),
        ),
    ]
