# Generated by Django 3.0.5 on 2021-01-08 12:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_profile_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='questionnaire_reasons',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
